# Generated by Selenium IDE

require 'selenium-webdriver'
require 'json'
describe 'sel' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'sel' do
    @driver.get('http://127.0.0.1:3000/num_finder/input')
    @driver.find_element(:id, 'ch').click
    @driver.find_element(:id, 'ch').send_keys('6')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, 'tbody:nth-child(5) td:nth-child(2)').text).to eq('3')
  end
end